# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: sre-lab
  region: ap-south-1
  version: "1.34"
vpc:
  id: "vpc-03898bdc7f0376737"
  subnets:
    private:
      ap-south-1a: { id: "subnet-0d20e096d27c39d6b" }
      ap-south-1b: { id: "subnet-0a3a1f80ba6ac6d3c" }
    public:
      ap-south-1a: { id: "subnet-0df23a38f32160380" }
      ap-south-1b: { id: "subnet-0845b18601f7d1b12" }
managedNodeGroups:
  - name: sre-workers
    instanceType: c7i-flex.large
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    privateNetworking: true   # nodes in private subnet
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy