apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-service
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deployments
    notifications.argoproj.io/subscribe.on-health-degraded.slack: alerts
spec:
  project: default
  source:
    repoURL: https://github.com/vinodpaltechops/sreproject.git
    targetRevision: HEAD
    path: trade-service/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trade-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true    # required for Argo Rollouts managed fields
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
