apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_ORG>/sre-lab-config
    targetRevision: HEAD
    path: k8s/trade-service
  destination:
    server: https://kubernetes.default.svc
    namespace: trade-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
